server:
  port: 8987
spring:
  application:
    name: API-ORDERS
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        cluster-name: default
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        cluster-name: default
  config:
    import:
      - optional:nacos:seata-client-orders.yml

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_orders?characterEncoding=UTF-8&useSSL=false
    username: root
    password: YUHW19980119

mybatis:
  mapper-locations: classpath:com/rs/mapper/*.xml
  type-aliases-package: com.rs.entity

logging:
  level:
    com.rs: debug
